name: Build
on: [push]
jobs:
  build:
    name: Elixir ${{matrix.elixir}} - OTP ${{matrix.otp}}
    runs-on: ubuntu-latest

    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        elixir:
          - "1.12.0"
          - "1.13.0"
        otp:
          - "24.3.4"

    services:
      fake-s3:
        image: lphoward/fake-s3
        ports: ["4569:4569"]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Dependencies
        run: mix deps.get

      - name: Compile
        run: mix compile --force --warnings-as-errors

      - name: Check formatting
        run: mix format --check-formatted

      - name: Test
        run: mix coveralls.github

      - name: Cache dialyzer
        uses: actions/cache@v2
        with:
          path: priv/plts
          key: plts-${{ matrix.elixir }}

      - name: Dialyzer
        run: mix dialyzer
